var _VARIABLES = {
  input: document.getElementById("input__task"),
  buttonAdd: document.getElementById("add"),
  list: document.getElementById("ol"),
  allList: document.getElementById("all"),
  activeList: document.getElementById("active"),
  completedList: document.getElementById("completed"),
  pages: document.getElementById("pages"),
  pageButtons: document.getElementsByClassName("page__noActive"),

  ice: document.getElementById("ice"),
  rainbow: document.getElementById("rainbow"),
  forest: document.getElementById("forest"),
  space: document.getElementById("space"),
  black: document.getElementById("black"),
  blue: document.getElementById("blue"),
  pink: document.getElementById("pink"),
  panda: document.getElementById("panda"),
  menu: document.getElementById("menu"),
  menuBtn: document.getElementById("menuBtn"),
  closeBtn: document.getElementById("closeBtn"),
};
